run:
  deadline: 10m

issues:
  max-same-issues: 0
  max-per-linter: 0
  exclude-use-default: false

  exclude-rules:
    - linters:
        - govet
      text: 'shadow: declaration of "err"'

    # we remove a few annoying things from our tests, because they
    # don't provide much beside complexity
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - goerr113
        - forcetypeassert

    - path: _test\.go
      text: "fieldalignment: struct"

    # No need to check for non-wrapped errors in cmd/ since most
    # command might return inline errors
    - path: cmd/
      linters:
        - goerr113
      text: "do not define dynamic errors"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck

    - bodyclose
    - stylecheck
    - gosec
    - unconvert
    - asciicheck
    - goimports
    - misspell
    - unparam
    - dogsled
    - prealloc
    - gocritic
    - gochecknoinits
    - whitespace
    - goprintffuncname
    - goerr113
    - exhaustive
    - nolintlint
    - noctx
    - exportloopref
    - gofumpt # replaces gofmt
    - tparallel
    - errorlint
    - revive # replaces golint
    - durationcheck
    - forbidigo
    - forcetypeassert
    - nilerr

linters-settings:
  govet:
    enable-all: true

  # for G306 and G301: https://github.com/golangci/golangci-lint/issues/177
  gosec:
    excludes:
      - G104 # this is a duplicate of errcheck
      - G304 # warns about file inclusion via variable. It basically blocks every `os.File(variable)`
      - G401 # warns about unsecure hash method. git requires the use of SHA1
      - G505 # warns about the use of SHA1. git works using SHA1
    config:
      G301: "0755" # git creates directories with the permission 0755, so this is what we're targeting for
      G306: "0644" # git creates files with the permission 0644, so this is what we're targeting for

  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - style
      - experimental
      - opinionated

    disabled-checks:
      - sloppyReassign
      - emptyFallthrough
      - octalLiteral
      - hugeParam # disabled because we pass option objects by copy
