version: "2"

tasks:
  build:
    cmds:
      - CGO_ENABLED=0 go build -v -o ./bin/git github.com/Nivl/git-go/cmd/git-go

  install:
    cmds:
      - CGO_ENABLED=0 go install github.com/Nivl/go-git/cmd/git-go

  test:
    cmds:
      # -race requires cgo
      - go test -race -mod=readonly ./...

  deps-upgrade:
    cmds:
      - go get -t -u ./...
      - go mod tidy

  dev:
    deps: [build]
    sources:
      - ./**/*.go
      - go.mod
