version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:2020.01
  macos:
    macos:
      xcode: 12.2.0
  silicon:
    macos:
      xcode: 12.0.0-beta

orbs:
  win: circleci/windows@2.2.0
  go: circleci/go@1.5.0
  codecov: codecov/codecov@1.1.3

jobs:
  test:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - go/install
      - go/load-cache
      - go/mod-download
      - go/save-cache

      - go/test:
          covermode: atomic
          race: true
          parallel: "100"

workflows:
  build:
    jobs:
      - test:
          matrix:
            parameters:
              os: [macos, silicon, linux]
# steps:
#   - checkout
#   - go/load-cache
#   - go/mod-download
#   - go/save-cache

#   - go/test:
#       covermode: atomic
#       race: true
#       parallel: 100

# - codecov/upload:
#   file: cover-source.out
