name: Config Validation
on: [push]
jobs:
  codecov:
    name: "Codecov.yml"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate codecov.yml
        id: response
        run: curl --data-binary @codecov.yml https://codecov.io/validate

      - name: Set Failure Code
        if: startsWith(steps.response , "Valid!") == false
        run: exit 1
