name: Config Validation
on: [push]
jobs:
  codecov:
    name: "Codecov.yml"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate codecov.yml
        uses: wei/curl@master
        with:
          args: --data-binary @codecov.yml https://codecov.io/validate
