name: Config Validation
on: [push]
jobs:
  codecov:
    name: "Codecov"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate codecov.yml
        run: curl --data-binary @codecov.yml https://codecov.io/validate
