name: Go
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Build
        run: go build -race ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          CC_TEST_REPORTER_ID_2: ${{ secrets.CC_TEST_REPORTER_ID_2 }}

      - name: Download Code climate code coverage reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Test
        run: go test -v -race -coverprofile c.out ./...

      - name: Report coverage
        run: ./cc-test-reporter after-build -p github.com/Nivl/git-go/ -r $env:CC_TEST_REPORTER_ID_2
