name: Go
on: [push]
jobs:
  go-vulnerabilities-scan:
    name: "Golang Vulnerabilities Scan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Generate go.list
        run: go list -json -m all > go.list
      - name: Run Nancy
        uses: sonatype-nexus-community/nancy-github-action@main

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.34

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - name: Build
        run: go build -race ./...

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - name: Test
        run: go test -race -timeout 3m -coverprofile coverage.txt ./...

      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          verbose: true
