name: Go
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Build
        run: go build -race ./...

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Test
        run: go test -v -race -coverprofile cc.${{ matrix.os }}.out ./...

      - name: Upload test results
        uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: cc.${{ matrix.os }}.out

  coverage:
    name: Upload test coverage
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Download test-results
        uses: actions/download-artifact@v1
        with:
          name: test-results

      - name: Download Code climate code coverage reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter

      - name: Report coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          GIT_COMMIT_SHA: ${{ github.sha }}
        with:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
        run: |
          ./cc-test-reporter format-coverage -p github.com/Nivl/git-go/ -t gocov test-results/cc.macos-latest.out > test-results/cc.macos-latest.json
          ./cc-test-reporter format-coverage -p github.com/Nivl/git-go/ -t gocov test-results/cc.windows-latest.out > test-results/cc.windows-latest.json
          ./cc-test-reporter format-coverage -p github.com/Nivl/git-go/ -t gocov test-results/cc.ubuntu-latest.out > test-results/cc.ubuntu-latest.json
          ./cc-test-reporter sum-coverage -p 3 test-results/cc.*.json -o cc.json
          ./cc-test-reporter upload-coverage --i cc.json


          ./cc-test-reporter format-coverage -p github.com/Nivl/git-go/ -t gocov test-results/cc.*.json
