name: Linter
on: [push]
jobs:
  lint:
    name: Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Go version
        run: echo "GO_VERSION='^$(grep 'go 1.' go.mod | cut -d ' ' -f 2)'" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.4.0
        with:
          version: v1.37

  codecov:
    name: "Codecov.yml"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate codecov.yml
        id: codecov
        run: |
          response=$(curl --data-binary @codecov.yml https://codecov.io/validate)
          response="${response//'%'/'%25'}"
          response="${response//$'\n'/%0A}"
          response="${response//$'\r'/'%0D'}"
          echo "::set-output name=response::${response}"

      - name: Set Failure Code
        if: "!startsWith(steps.codecov.outputs.response , 'Valid!')"
        run: |
          echo "${{ steps.codecov.outputs.response }}"
          exit 1
