name: Linter
on: [push]
jobs:
  lint:
    name: Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Get Go version
        id: gover
        run: echo "::set-output name=value::^$(grep 'go 1.' go.mod | cut -d ' ' -f 2)"
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.gover.outputs.value }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.42.0

  codecov:
    name: "Codecov.yml"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Validate codecov.yml
        id: codecov
        run: |
          response=$(curl --data-binary @codecov.yml https://codecov.io/validate)
          response="${response//'%'/'%25'}"
          response="${response//$'\n'/%0A}"
          response="${response//$'\r'/'%0D'}"
          echo "::set-output name=response::${response}"

      - name: Set Failure Code
        if: "!startsWith(steps.codecov.outputs.response , 'Valid!')"
        run: |
          echo "${{ steps.codecov.outputs.response }}"
          exit 1
